CREATE PROCEDURE VALIDAR_USUARIO
@NOMBRE_USUARIO NVARCHAR(50),
@PASSWORD NVARCHAR(50),
@RESULTADO BIT OUTPUT
AS 
BEGIN

	IF EXISTS(
		SELECT 1 
		FROM ProyectoLUG.Usuarios AS US
		WHERE US.nombreUsuario = @NOMBRE_USUARIO AND US.password = @PASSWORD
	)
	BEGIN 
		SET @RESULTADO = 1;
	END 
	ELSE 
	BEGIN
		SET @RESULTADO = 0;
	END
END;

