USE [FACULTAD]
GO
/****** Object:  StoredProcedure [dbo].[VALIDAR_USUARIO]    Script Date: 9/6/2023 7:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER OR CREATE PROCEDURE [dbo].[VALIDAR_USUARIO]
@NOMBRE_USUARIO NVARCHAR(50),
@PASSWORD NVARCHAR(50)

AS 
BEGIN

	IF EXISTS(
		SELECT 1 
		FROM ProyectoLUG.Usuarios AS US
		WHERE US.nombreUsuario = @NOMBRE_USUARIO AND US.password = @PASSWORD
	)
	BEGIN 
		SELECT 1; --EXISTE EL USUARIO
	END 
	ELSE 
	BEGIN
		SELECT 0; --NO EXISTE EL USUARIO
	END	
END;