USE FACULTAD
select * from proyectoLug.usuarios

INSERT INTO PROYECTOLUG.USUARIOS
VALUES(1, 'MARCOS IANNELLO' , 'ADMIN1234'),
(2, 'JUAN BERTERRE' , 'ADMIN1234'),
(3, 'USER' , 'USER1234')

SELECT * FROM PROYECTOLUG.PERMISOS

INSERT INTO PROYECTOLUG.PERMISOS
VALUES(1, 'ADMIN'),
(2, 'USER')

SELECT * FROM PROYECTOLUG.Permiso_Usuario

INSERT INTO PROYECTOLUG.Permiso_Usuario
VALUES (1,1,1),
(2,2,1),
(3,3,2)

SELECT * FROM PROYECTOLUG.COMIC
INSERT INTO PROYECTOLUG.COMIC
VALUES(1,'PRUEBA','ACCION','DC','COMIC_DC')